#!/bin/bash

# Synchronizes the local ani-cli history with the remote history.

## if the files are identical, exit the script
cmp --silent ani-hsts ani-hsts.b && (git add . && git commit -m "-" && git push && exit 0) || echo "same"
