#!/bin/bash

# Synchronizes the local ani-hsts file with the remote repository

set -e

FILE="ani-hsts"
BACKUP="$FILE.b"

git pull -q

if ! cmp -s "$FILE" "$BACKUP"; then

  cp "$FILE" "$BACKUP"

  git add "$FILE" > /dev/null
  git commit -m "$FILE updated" -q
  git push -q
fi

